spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

server:
  servlet:
    context-path: /accounts
  port: 8083

feign:
  hystrix:
    enabled: true
